[package]
name = "kvs"
version = "0.1.0"
authors = ["qw4990 <qw4990@163.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"

[dev-dependencies]
tempfile = "3.0.7"
walkdir = "2.2.7"
assert_cmd = "0.11"
predicates = "1.0.0"